// services/b2cRealEstateData.ts — Default B2C Real Estate Grounded Knowledge Base
// Multi-sheet relational data model + target website content for consumer conversion,
// unit availability, pricing, and payment plans (filtering out audit/governance logs).

import { SalesRecord, RelationalDataModel, ScrapedWebContext } from '../types';
import { buildRelationalDataModel } from './relationalModelEngine';

// ─── Sheet 1: Real Estate Units & Inventory ──────────────────────────
export const B2C_REAL_ESTATE_UNITS: SalesRecord[] = [
  {
    unitCode: 'MH-101',
    propertyName: 'Marina Horizon Residences',
    propertyType: '1-Bedroom Luxury Apartment',
    bedrooms: 1,
    bathrooms: 2,
    areaSqFt: 840,
    floor: 10,
    view: 'Marina Skyline & Promenade',
    price: 1350000,
    bookingDeposit: 135000,
    monthlyInstallment: 11250,
    paymentPlanCode: 'PLAN-8020-POST',
    handoverDate: 'Q4 2025',
    status: 'Available',
    featuredAmenity: 'Private Balcony, Smart Automation & Infinity Pool Access',
    location: 'Dubai Marina',
    date: '2025-01-15',
    revenue: 1350000,
    cost: 880000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Marina District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'MH-102',
    propertyName: 'Marina Horizon Residences',
    propertyType: '2-Bedroom Waterfront Suite',
    bedrooms: 2,
    bathrooms: 3,
    areaSqFt: 1380,
    floor: 14,
    view: 'Full Marina & Yacht Club',
    price: 1980000,
    bookingDeposit: 198000,
    monthlyInstallment: 16500,
    paymentPlanCode: 'PLAN-8020-POST',
    handoverDate: 'Q4 2025',
    status: 'Available',
    featuredAmenity: 'Floor-to-Ceiling Glass, Valet Parking & Concierge',
    location: 'Dubai Marina',
    date: '2025-01-18',
    revenue: 1980000,
    cost: 1280000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Marina District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'MH-PH01',
    propertyName: 'Marina Horizon Residences',
    propertyType: 'Signature Sky Penthouse',
    bedrooms: 4,
    bathrooms: 5,
    areaSqFt: 3850,
    floor: 42,
    view: '360° Marina, Sea & Palm Jumeirah',
    price: 6200000,
    bookingDeposit: 620000,
    monthlyInstallment: 51600,
    paymentPlanCode: 'PLAN-6040-CON',
    handoverDate: 'Q4 2025',
    status: 'Limited Units',
    featuredAmenity: 'Private Rooftop Pool, Sky Terrace, Private Elevator',
    location: 'Dubai Marina',
    date: '2025-01-20',
    revenue: 6200000,
    cost: 3900000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Marina District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'AP-204',
    propertyName: 'Azure Palms Beachfront',
    propertyType: '2-Bedroom Beachfront Residence',
    bedrooms: 2,
    bathrooms: 2.5,
    areaSqFt: 1520,
    floor: 5,
    view: 'Direct Ocean & Sunset Beach',
    price: 2450000,
    bookingDeposit: 245000,
    monthlyInstallment: 20400,
    paymentPlanCode: 'PLAN-8020-POST',
    handoverDate: 'Q2 2026',
    status: 'Available',
    featuredAmenity: 'Direct Private Beach Access, Beach Cabana Service',
    location: 'Palm Jumeirah',
    date: '2025-02-01',
    revenue: 2450000,
    cost: 1600000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Palm District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'AP-308',
    propertyName: 'Azure Palms Beachfront',
    propertyType: '3-Bedroom Royal Sky Villa',
    bedrooms: 3,
    bathrooms: 4,
    areaSqFt: 2420,
    floor: 12,
    view: 'Panoramic Palm Crescent & Sea',
    price: 4100000,
    bookingDeposit: 410000,
    monthlyInstallment: 34100,
    paymentPlanCode: 'PLAN-8020-POST',
    handoverDate: 'Q2 2026',
    status: 'Available',
    featuredAmenity: 'Wrap-around Terrace, Jacuzzi, Italian Marble Bathrooms',
    location: 'Palm Jumeirah',
    date: '2025-02-05',
    revenue: 4100000,
    cost: 2650000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Palm District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'CR-105',
    propertyName: 'Creek Royal Mansions',
    propertyType: '1-Bedroom Garden Apartment',
    bedrooms: 1,
    bathrooms: 1.5,
    areaSqFt: 780,
    floor: 3,
    view: 'Creek Park & Historic Waterway',
    price: 1180000,
    bookingDeposit: 118000,
    monthlyInstallment: 9830,
    paymentPlanCode: 'PLAN-READY-5050',
    handoverDate: 'Ready to Move',
    status: 'Available',
    featuredAmenity: 'Private Garden Patio, Metro Station 2 Mins Walk',
    location: 'Dubai Creek Harbour',
    date: '2025-02-10',
    revenue: 1180000,
    cost: 790000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Creek District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'CR-402',
    propertyName: 'Creek Royal Mansions',
    propertyType: '2-Bedroom Luxury Residence',
    bedrooms: 2,
    bathrooms: 2.5,
    areaSqFt: 1290,
    floor: 18,
    view: 'Burj Khalifa Skyline & Creek Tower',
    price: 1820000,
    bookingDeposit: 182000,
    monthlyInstallment: 15160,
    paymentPlanCode: 'PLAN-READY-5050',
    handoverDate: 'Ready to Move',
    status: 'Available',
    featuredAmenity: 'Central Boulevard Access, Yacht Marina Promenade',
    location: 'Dubai Creek Harbour',
    date: '2025-02-12',
    revenue: 1820000,
    cost: 1220000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Creek District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'DS-2201',
    propertyName: 'Downtown Sky Tower',
    propertyType: 'Studio Executive Suite',
    bedrooms: 0,
    bathrooms: 1,
    areaSqFt: 540,
    floor: 22,
    view: 'Downtown City Skyline',
    price: 980000,
    bookingDeposit: 98000,
    monthlyInstallment: 8160,
    paymentPlanCode: 'PLAN-INVEST-VISA',
    handoverDate: 'Q1 2026',
    status: 'Available',
    featuredAmenity: 'High Rental Yield (~9%), Fully Furnished Designer Option',
    location: 'Downtown Boulevard',
    date: '2025-02-15',
    revenue: 980000,
    cost: 650000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Downtown District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'DS-3505',
    propertyName: 'Downtown Sky Tower',
    propertyType: '3-Bedroom Boulevard Residence',
    bedrooms: 3,
    bathrooms: 3.5,
    areaSqFt: 2150,
    floor: 35,
    view: 'Full Burj Khalifa & Dubai Fountain View',
    price: 3650000,
    bookingDeposit: 365000,
    monthlyInstallment: 30400,
    paymentPlanCode: 'PLAN-6040-CON',
    handoverDate: 'Q1 2026',
    status: 'Reserved',
    featuredAmenity: 'Direct Air-Conditioned Mall Walkway, Infinity Deck',
    location: 'Downtown Boulevard',
    date: '2025-02-18',
    revenue: 3650000,
    cost: 2350000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Downtown District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'HL-G06',
    propertyName: 'The Hills Golf Villas',
    propertyType: '4-Bedroom Luxury Villa',
    bedrooms: 4,
    bathrooms: 5,
    areaSqFt: 4600,
    floor: 2,
    view: '18-Hole Championship Golf Course & Lakes',
    price: 5450000,
    bookingDeposit: 545000,
    monthlyInstallment: 45400,
    paymentPlanCode: 'PLAN-8020-POST',
    handoverDate: 'Q3 2026',
    status: 'Available',
    featuredAmenity: 'Private Swimming Pool, Landscaped Garden, 2-Car Garage',
    location: 'Dubai Hills Estate',
    date: '2025-02-20',
    revenue: 5450000,
    cost: 3550000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Hills District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'HL-G12',
    propertyName: 'The Hills Golf Villas',
    propertyType: '5-Bedroom Signature Estate Villa',
    bedrooms: 5,
    bathrooms: 6.5,
    areaSqFt: 6200,
    floor: 2,
    view: 'Fairway Green & Central Lake',
    price: 7800000,
    bookingDeposit: 780000,
    monthlyInstallment: 65000,
    paymentPlanCode: 'PLAN-8020-POST',
    handoverDate: 'Q3 2026',
    status: 'Limited Units',
    featuredAmenity: 'Double-Height Ceilings, Maid & Driver Quarters, Wine Cellar',
    location: 'Dubai Hills Estate',
    date: '2025-02-25',
    revenue: 7800000,
    cost: 4950000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Hills District',
    customerName: 'Direct Buyer Inquiries'
  },
  {
    unitCode: 'MH-203',
    propertyName: 'Marina Horizon Residences',
    propertyType: '2-Bedroom Waterfront Suite',
    bedrooms: 2,
    bathrooms: 2.5,
    areaSqFt: 1410,
    floor: 20,
    view: 'Marina Yacht Harbour',
    price: 2050000,
    bookingDeposit: 205000,
    monthlyInstallment: 17080,
    paymentPlanCode: 'PLAN-8020-POST',
    handoverDate: 'Q4 2025',
    status: 'Available',
    featuredAmenity: 'Modern Fitted Kitchen with German Appliances',
    location: 'Dubai Marina',
    date: '2025-03-01',
    revenue: 2050000,
    cost: 1320000,
    discount: 0,
    creditDays: 0,
    outstandingAmount: 0,
    region: 'Marina District',
    customerName: 'Direct Buyer Inquiries'
  }
];

// ─── Sheet 2: B2C Real Estate Payment Plans ───────────────────────────
export const B2C_PAYMENT_PLANS = [
  {
    planId: 'PLAN-8020-POST',
    planName: '80/20 Flexible Post-Handover (3 Years)',
    downPaymentPct: 10,
    duringConstructionPct: 40,
    onHandoverPct: 30,
    postHandoverPct: 20,
    postHandoverMonths: 36,
    dldWaiverPct: 100,
    agencyCommission: '0% Zero Commission',
    guaranteedYield: '8.0% Net Yield Support',
    eligibility: 'All Buyers & Investors (UAE & International)',
    keyFeature: 'Pay 10% on booking, 40% across milestones, and move in paying remaining over 36 months'
  },
  {
    planId: 'PLAN-6040-CON',
    planName: '60/40 Construction-Linked Standard',
    downPaymentPct: 20,
    duringConstructionPct: 40,
    onHandoverPct: 40,
    postHandoverPct: 0,
    postHandoverMonths: 0,
    dldWaiverPct: 100,
    agencyCommission: '0% Zero Commission',
    guaranteedYield: '7.5% Yield Projection',
    eligibility: 'Cash & Mortgage Approved Buyers',
    keyFeature: 'Highest upfront discount (3% cash incentive) with 0% post-handover interest'
  },
  {
    planId: 'PLAN-READY-5050',
    planName: 'Ready Move 50/50 Handover Scheme',
    downPaymentPct: 20,
    duringConstructionPct: 0,
    onHandoverPct: 30,
    postHandoverPct: 50,
    postHandoverMonths: 24,
    dldWaiverPct: 50,
    agencyCommission: '0% Zero Commission',
    guaranteedYield: 'Immediate Rental Income upon Handover',
    eligibility: 'Ready to Move Inventory in Creek Harbour & Downtown',
    keyFeature: 'Receive keys immediately upon paying 50%, spread remaining 50% over 2 years'
  },
  {
    planId: 'PLAN-INVEST-VISA',
    planName: '10-Year UAE Golden Visa Investor Plan',
    downPaymentPct: 20,
    duringConstructionPct: 30,
    onHandoverPct: 50,
    postHandoverPct: 0,
    postHandoverMonths: 0,
    dldWaiverPct: 100,
    agencyCommission: '0% Zero Commission',
    guaranteedYield: '8.5% Guaranteed Net Rental Return (3 Years)',
    eligibility: 'Investments >= 2,000,000 for Buyer and Immediate Family Visa',
    keyFeature: 'Guaranteed 10-Year Golden Visa application processing included with purchase'
  }
];

// ─── Sheet 3: Developments & Projects ────────────────────────────────
export const B2C_DEVELOPMENTS = [
  {
    projectCode: 'DEV-MH',
    projectName: 'Marina Horizon Residences',
    location: 'Dubai Marina Waterfront',
    developer: 'Horizon Luxury Developments',
    completionYear: '2025',
    totalUnits: 280,
    startingPrice: 1350000,
    lifestyleAmenities: 'Private Yacht Berths, Infinity Edge Pool, Spa, Cinema, Valet Parking',
    distanceToAirport: '25 Mins to DXB',
    handoverMilestone: '85% Structural Completion'
  },
  {
    projectCode: 'DEV-AP',
    projectName: 'Azure Palms Beachfront',
    location: 'Palm Jumeirah West Crescent',
    developer: 'Azure Island Living',
    completionYear: '2026',
    totalUnits: 140,
    startingPrice: 2450000,
    lifestyleAmenities: 'Private White Sand Beach, Beachfront Dining, Tennis Courts, Concierge',
    distanceToAirport: '30 Mins to DXB',
    handoverMilestone: '65% Structural Completion'
  },
  {
    projectCode: 'DEV-CR',
    projectName: 'Creek Royal Mansions',
    location: 'Dubai Creek Harbour',
    developer: 'Royal Creek Estates',
    completionYear: 'Ready to Move',
    totalUnits: 320,
    startingPrice: 1180000,
    lifestyleAmenities: 'Central Park Access, Boulevard Retail, Waterfront Promenade, Kids Play Area',
    distanceToAirport: '12 Mins to DXB',
    handoverMilestone: '100% Ready for Immediate Occupancy'
  },
  {
    projectCode: 'DEV-DS',
    projectName: 'Downtown Sky Tower',
    location: 'Downtown Boulevard',
    developer: 'Skyline Capital Assets',
    completionYear: '2026',
    totalUnits: 450,
    startingPrice: 980000,
    lifestyleAmenities: 'Burj Khalifa View Lounge, Direct Mall Airbridge, Helipad, Rooftop Sky Gym',
    distanceToAirport: '15 Mins to DXB',
    handoverMilestone: '70% Construction Completed'
  },
  {
    projectCode: 'DEV-HL',
    projectName: 'The Hills Golf Villas',
    location: 'Dubai Hills Estate',
    developer: 'Green Fairways Residential',
    completionYear: '2026',
    totalUnits: 95,
    startingPrice: 5450000,
    lifestyleAmenities: '18-Hole Championship Golf Course, Clubhouse, International School Access',
    distanceToAirport: '20 Mins to DXB',
    handoverMilestone: '60% Construction Completed'
  }
];

// ─── Sheet 4: Consumer Buyer Inquiries & Conversion Pipeline ────────
export const B2C_CONSUMER_INQUIRIES = [
  {
    inquiryId: 'INQ-5001',
    customerName: 'Marcus Vance',
    preferredType: '2-Bedroom Waterfront Suite',
    budgetMax: 2200000,
    financingNeeded: 'Post-Handover Plan Preferred',
    targetMoveIn: 'Q4 2025',
    preferredPaymentPlan: '80/20 Flexible Post-Handover',
    leadStatus: 'Tour Scheduled',
    consultant: 'Sarah Al-Mansoor',
    notes: 'High conversion intent. Wants 14th floor Marina view unit MH-102.'
  },
  {
    inquiryId: 'INQ-5002',
    customerName: 'Elena Rostova',
    preferredType: 'Signature Sky Penthouse',
    budgetMax: 6500000,
    financingNeeded: 'Cash Buyer / Golden Visa',
    targetMoveIn: 'Immediate or Q4 2025',
    preferredPaymentPlan: '10-Year UAE Golden Visa Investor Plan',
    leadStatus: 'Offer Submitted',
    consultant: 'David Chen',
    notes: 'Qualifying for family Golden Visa. Deposit prepared for MH-PH01.'
  },
  {
    inquiryId: 'INQ-5003',
    customerName: 'Tariq Al-Khatib',
    preferredType: '1-Bedroom Luxury Apartment',
    budgetMax: 1400000,
    financingNeeded: '10% Booking Deposit Ready',
    targetMoveIn: 'Q4 2025',
    preferredPaymentPlan: '80/20 Flexible Post-Handover',
    leadStatus: 'Deposit Placed',
    consultant: 'Sarah Al-Mansoor',
    notes: 'Locked Unit MH-101 with 135,000 booking deposit.'
  },
  {
    inquiryId: 'INQ-5004',
    customerName: 'James & Claire Bennett',
    preferredType: '4-Bedroom Luxury Villa',
    budgetMax: 5800000,
    financingNeeded: 'Construction-Linked Plan',
    targetMoveIn: 'Q3 2026',
    preferredPaymentPlan: '80/20 Flexible Post-Handover',
    leadStatus: 'VIP Presentation Requested',
    consultant: 'Alex Rossi',
    notes: 'Relocating family. Interested in The Hills Golf Villas HL-G06.'
  }
];

// ─── Default Pre-Loaded Multi-Sheet Relational Data Model ─────────────
export const DEFAULT_B2C_RELATIONAL_MODEL: RelationalDataModel = buildRelationalDataModel({
  'Units_Inventory': B2C_REAL_ESTATE_UNITS,
  'Payment_Plans': B2C_PAYMENT_PLANS,
  'Developments_Projects': B2C_DEVELOPMENTS,
  'Consumer_Inquiries': B2C_CONSUMER_INQUIRIES
}, 'Real_Estate_AI_Filled_Dataset_AI_KPI_Template_Final.xlsx');

// ─── Default Pre-Grounded B2C Real Estate Web Context ────────────────
export const DEFAULT_B2C_WEB_CONTEXT: ScrapedWebContext = {
  url: 'https://saimabuilders.net/',
  finalUrl: 'https://saimabuilders.net/',
  title: 'Saima Builders and Developers | Real Estate Experts',
  metaDescription: 'Defining the Standards of Real Estate Development. Explore signature residential towers, luxury apartments, and housing schemes with flexible installment plans and developer-direct booking.',
  status: 'active',
  scrapedAt: 'Synchronized & Grounded Live',
  wordCount: 1680,
  domSummary: 'Saima Builders and Developers grounded portal. Features residential apartment towers, commercial avenues, flexible consumer booking plans, and direct buyer inquiries.',
  headings: [
    { level: 1, text: 'Defining the Standards of Real Estate Development' },
    { level: 2, text: 'A Word About Saima Group' },
    { level: 2, text: 'Explore our recent projects & residential towers' },
    { level: 2, text: 'Where Innovation, Sustainability, and Community Meet' },
    { level: 2, text: 'Flexible Consumer Installment Plans with Developer Booking Guarantee' },
    { level: 3, text: 'Executive 1, 2, 3 & 4 Bedroom Apartments and Luxury Penthouses' },
    { level: 3, text: 'Direct Developer Booking — 0% Broker Commission' }
  ],
  pricingSignals: [
    'Executive 1-Bedroom Apartments from 980,000 (10% Initial Booking Deposit: 98,000)',
    'Luxury 2-Bedroom Tower Residences from 1,820,000 with 36-Month Flexible Installments',
    'Royal 3-Bedroom Family Suites from 3,650,000 with Prime Skyline View',
    'Signature Sky Penthouses from 6,200,000 with Private Terrace',
    '4-Bedroom Luxury Villas from 5,450,000',
    'Zero Commission (0%) & Direct Developer Registration Incentive'
  ],
  keyFacts: [
    '10% initial booking deposit reserves unit with immediate contract issuance',
    'Flexible 80/20 payment plan allows paying remaining 20% over 36 monthly installments post-handover',
    'Modern architectural designs with integrated lifestyle amenities, gymnasiums, and high-speed elevators',
    'Ready-to-move and under-construction inventory across prime metropolitan locations',
    'Transparent pricing structures with zero hidden fees and direct developer customer support',
    'Dedicated property consultant assistance for on-site tours and mortgage advisory'
  ],
  tables: [
    {
      headers: ['Project Category', 'Configurations', 'Area (Sq Ft)', 'Starting Price', 'Monthly Installment (3-Yr Plan)'],
      rows: [
        ['Executive Studio', 'Studio', '540 sq ft', '980,000', '8,160 / month'],
        ['Luxury 1-Bedroom', '1 BR', '780 - 840 sq ft', '1,180,000', '9,830 / month'],
        ['Waterfront 2-Bedroom', '2 BR', '1,290 - 1,410 sq ft', '1,820,000', '15,160 / month'],
        ['Royal 3-Bedroom', '3 BR', '2,150 - 2,420 sq ft', '3,650,000', '30,400 / month'],
        ['Signature Penthouse', '4 BR', '3,850 sq ft', '6,200,000', '51,600 / month'],
        ['Fairway Golf Villa', '4-5 BR', '4,600 - 6,200 sq ft', '5,450,000', '45,400 / month']
      ]
    },
    {
      headers: ['Milestone Phase', 'Payment Breakdown', 'Estimated Timeline', 'Consumer Advantage'],
      rows: [
        ['Booking Deposit', '10%', 'On Unit Reservation', 'Locks unit, price protection guarantee, 0% commission'],
        ['Construction Phase', '40%', 'Across Build Milestones', 'Staged installments linked to construction progress'],
        ['Handover & Key Receipt', '30%', 'At Handover (2025/2026)', 'Immediate move-in or rental occupancy'],
        ['Post-Handover Facility', '20%', 'Over 36 Months Post-Move', 'Spread remaining balance over 3 years']
      ]
    }
  ],
  sanitizedText: `Saima Builders and Developers | Defining the Standards of Real Estate Development.
Leading real estate developer delivering premier residential towers, commercial plazas, and gated communities.
Specializing in consumer-focused housing solutions with transparent pricing, guaranteed unit availability, and flexible payment plans.
Explore signature 1, 2, 3, and 4-bedroom apartments and sky penthouses with modern amenities, round-the-clock security, and dedicated parking.
Consumer payment plans include flexible down payments from 10%, construction-linked milestones, and 3-year post-handover options. All bookings are direct with the developer with 0% broker commission.`
};
